---
# The Mongodb Playbook
- name: MongoDB | Import Public keys
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: MongoDB | Add Repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org'
    repo: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" 
    state: present
    update_cache: yes

- name: MongoDB | Install MongoDB
  apt: 
    name: mongodb-server
    state: present
    update_cache: yes

- name: MongoDB | Running State
  service:
    name: mongodb
    state: started
