---
- name: Package prerequisites for node.js
  action: apt pkg=python-software-properties state=installed update-cache=yes

- name: Install nodejs along with npm with shell
  shell: |
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs

- name: Install pm2 package globally
  become: yes
  npm: 
    executable: /usr/bin/npm
    global: true
    name: '{{ item }}'
    state: present
  with_items:
    - pm2

