---
- hosts: production
  user: vagrant
  become_method: sudo
  vars:
    project_path: ~/nodejs
  become: yes
  roles:
    - role: ansible-nginx
    - role: ansible-softwares
    - role: ansible-mongodb
    - role: DavidWittman.redis
    - role: ansible-nodejs
    - role: ansible-nodejs-apps
      # apps:
      #   enabled:
      #     - "/srv/myapp/"
      #     - "/srv/anotherapp/"
